name: pr-test
on: pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: /
          # check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
          # skip_check: CKV_AWS_1 # optional: skip a specific check_id. can be comma separated list
          # quiet: true # optional: display only failed checks
          # soft_fail: true # optional: do not return an error code if there are failed checks
          # framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          # output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only
          # download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          # log_level: DEBUG # optional: set log level. Default WARNING
#name: tfsec
#on: pull_request
#jobs:
#  tfsec:
#    name: runner / tfsec
#    runs-on: ubuntu-latest

#    steps:
#      - name: Clone repo
#        uses: actions/checkout@master

#      - name: tfsec
#        uses: reviewdog/action-tfsec@master
#        with:
#          github_token: ${{ secrets.github_token }}
#          working_directory: "testdata" # Change working directory
#          reporter: github-pr-review # Change reporter
#          fail_on_error: "true" # Fail action if errors are found
#          filter_mode: "nofilter" # Check all files, not just the diff
#          flags: "" # Optional
